set encoding=utf-8
set nocompatible              

set clipboard=unnamed


set textwidth=80
set colorcolumn=+1
set backspace=2
set number
set nobackup
set nowritebackup
set noswapfile
set history=50
set laststatus=2
set ruler
set autowrite

set tabstop=4
set shiftwidth=4
set shiftround
set expandtab
set nojoinspaces
set smartindent
set autoindent

set splitbelow
set splitright
set guicursor+=n-v-c:blinkon0

nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

filetype off

call plug#begin('$HOME/vimfiles/bundle')
Plug 'scrooloose/nerdTree'
Plug 'tomasr/molokai'
Plug 'Valloric/YouCompleteMe'
call plug#end()            

colorscheme molokai

if has ("gui_running")
    if has("gui_gtk2")
        set guifont=Inconsolata\ 12
    elseif has("gui_win32")
        set guifont=Consolas:h12
    endif
endif
