set nocompatible              
set textwidth=80
set colorcolumn=+1
set backspace=2
set number
set nobackup
set nowritebackup
set noswapfile
set history=50
set laststatus=2
set ruler
set autowrite

set tabstop=4
set shiftwidth=4
set shiftround
set expandtab
set nojoinspaces
set smartindent
set autoindent

set splitbelow
set splitright
set guicursor+=n-v-c:blinkon0
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

filetype off

if has('win32')
    set runtimepath=$HOME/.vim, $VIM/vimfiles, $VIMRUNTIME, $VIM/vimfiles/after, $HOME/.vim/after
endif

"If plug-vim does not exist, download it.
if empty(glob('$HOME/.vim/autoload/plug.vim'))
    silent !curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('$HOME/.vim/bundle')
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdTree'
Plug 'tomasr/molokai'
Plug 'kien/ctrlp.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()            

colorscheme molokai

if has ("gui_running")
    if has("gui_gtk2")
        set guifont=Inconsolata\ 12
    elseif has("gui_win32")
        set guifont=Consolas:h12
    endif
endif

let g:airline_theme='simple'
let g:airline_powerline_fonts=0
